image: node:18.20.4  # Base image for all jobs

stages:          
  - build
  - test
  - deploy

# Build job
build-job:       
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths: 
      - build/  # Artifacts for deployment

# Cypress test job
cypress-test-job:    
  image: cypress/browsers:node18.20.4-chrome85-ff81
  stage: test    
  script:
    - yarn install
    - yarn start &  # Start the app in the background
    - yarn cy:run  # Run Cypress tests
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 week
  allow_failure: false  # Ensure that this job fails the pipeline if tests fail

# Deploy job
deploy-job:      
  stage: deploy  
  script:
    - yarn global add vercel
    - vercel --prod --token $VERCEL_TOKEN
  only:
    - master  # Restrict deployment to master branch
  dependencies:   # Only run this job if the previous jobs succeed
    - build-job
    - cypress-test-job
  environment:
    name: production
    url: https://barebone-system.vercel.app
  when: on_success  # Deploy only if the test job succeeds