image: node:18.20.4

stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths: 
      - build/

cypress-test-job:    
  image: cypress/browsers:node18.20.4-chrome113-ff116
  stage: test    
  script:
    - yarn install
    - yarn start &  
    - yarn cy:run  
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 week
  allow_failure: false

deploy-job:      
  stage: deploy  
  script:
    - yarn global add vercel
    - vercel --prod --token $VERCEL_TOKEN
  only:
    - master  
  dependencies:   
    - build-job
    - cypress-test-job
  environment:
    name: production
    url: https://barebone-system.vercel.app
  when: on_success