image: node:18.20.4  # Using Node 18.20.4 as the base image for all jobs

stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths: 
      - build/  # This will be used for deployment

cypress-test-job:    
  image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
  stage: test    
  script:
    - rm -rf node_modules && npm ci  # Clean install to ensure consistency
    - npm start &  # Start the app in the background
    - npm run cy:run  # Run Cypress tests
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 week
  allow_failure: false  # Ensure that this job fails the pipeline if tests fail

deploy-job:      
  stage: deploy  
  script:
    - npm install -g vercel
    - vercel --prod --token $VERCEL_TOKEN
  only:
    - master  # Restrict deployment to master branch
  dependencies:   # Ensure that this job runs only if the previous jobs succeed
    - build-job
    - cypress-test-job
  environment:
    name: production
    url: https://barebone-system.vercel.app
  when: on_success  # Deploy only if the previous jobs succeed
