image: node:18.20.4  # Using Node 18.20.4 as the base image for all jobs

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/  # Use the dist folder as the artifact for deployment

cypress-test-job:
  image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn cy:test
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 week
  dependencies: 
    - build-job  # This ensures that tests run after the build
  timeout: 10m
  allow_failure: false  # Ensures pipeline fails if tests fail

deploy-job:
  stage: deploy
  only:
    - master  # Restrict deployment to the master branch
  script:
    - yarn global add vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  dependencies:
    - build-job
    - cypress-test-job
  environment:
    name: production
    url: https://barebone-system.vercel.app
  when: on_success