image: node:18.20.4  # Using Node 18.20.4 as the base image for all jobs

stages:          
  - build
  - test
  - deploy

# Build job
build-job:       
  stage: build
  script:
    - rm -rf node_modules  # Remove node_modules to ensure clean dependencies
    - yarn install --frozen-lockfile  # Ensure integrity and install dependencies using frozen lockfile
    - yarn build  # Build the project
  artifacts:
    paths: 
      - build/  # This will be used for deployment

# Cypress test job
cypress-test-job:    
  image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
  stage: test    
  script:
    - rm -rf node_modules  # Ensure a clean node_modules directory
    - yarn install --frozen-lockfile  # Reinstall dependencies with frozen lockfile to avoid issues with transitive deps
    - yarn start &  # Start the app in the background
    - yarn run cy:run  # Run Cypress tests
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4  # Store videos of tests
      - cypress/screenshots/**/*.png  # Store screenshots of failed tests
    expire_in: 1 week  # Keep artifacts for 1 week
  allow_failure: false  # Ensure that this job fails the pipeline if tests fail

# Deployment job
deploy-job:      
  stage: deploy  
  script:
    - yarn global add vercel  # Install Vercel globally using Yarn
    - vercel --prod --token $VERCEL_TOKEN  # Deploy to Vercel with the token
  only:
    - master  # Only deploy from the master branch
  dependencies:   # Only run this job if the previous jobs succeed
    - build-job
    - cypress-test-job
  environment:
    name: production
    url: https://barebone-system.vercel.app  # Production environment URL
  when: on_success  # Deploy only if the test job succeeds