image: node:18.20.4  # Using Node 18.20.4 as the base image for all jobs

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - build/  # This will be used for deployment

cypress-test-job:
  image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn run concurrently "yarn dev" "yarn cy:run"
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 week
  allow_failure: false  # Fail the pipeline if tests fail
  dependencies: 
    - build-job  # This ensures that tests run after the build

deploy-job:
  stage: deploy
  script:
    - yarn global add vercel
    - vercel --prod --token $VERCEL_TOKEN
  only:
    - master  # This restricts deployment to the master branch
  environment:
    name: production
    url: https://barebone-system.vercel.app
  when: on_success  # Deploy only if previous jobs succeed
  dependencies:
    - build-job
    - cypress-test-job
  dependencies:
    - build-job
    - cypress-test-job