image: node:18.20.4  # Using Node 18.20.4 as the base image for all jobs

stages:          
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths: 
      - build/  # This will be used for deployment

cypress-test-job:    
  image: cypress/browsers:node18.20.4-chrome85-ff81
  stage: test    
  script:
    - npm ci
    - npm start &  # Start the app in the background
    - npm run cy:run  # Run Cypress tests
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 week

deploy-job:      
  stage: deploy  
  script:
    - npm install -g vercel
    - vercel --prod --token $VERCEL_TOKEN
  only:
    - master  # This restricts deployment to the master branch
  environment:
    name: production
    url: https://barebone-system.vercel.app